### ISSUE TITLE
Writing Metadata onto Visualiser output

### ISSUE THREAD

**Issue by dalmouiee** [AustralianCancerDataNetwork/pydicer#74]
Write metadata about image in top-right white space for the imaging Visualiser:
- PatientID
- SeriesName
- StudyName
- StudyDate (Function in Dataset module that chooses appropriate date to select)
- MaximumDose

**Comment by pchlap** [comment]
Hi @Janetxxx, I know it's been a while since we have looked at the pydicer stuff together. But I know you had this part working fairly well? If it isn't too much effort it would be great if you could put a pull request in for this. Even if it isn't finished its no problem. We can use what is ready and can add to it later :)
